.\" Copyright (c) 2026 The FreeBSD Foundation
.\" 
.\" SPDX-License-Identifier: BSD-2-Clause
.\" 
.\" This software was developed by Benjamin Stürz <benni@stuerz.xyz>
.\" under sponsorship from the FreeBSD Foundation.
.Dd July 27, 2026
.Dt DUMPFS_EXT2FS 8
.Os
.Sh NAME
.Nm dumpfs_ext2fs
.Nd dump ext2fs file system information
.Sh SYNOPSIS
.Sh DESCRIPTION
.Sh SEE ALSO
.Xr ext2fs 4 ,
.Xr dumpfs 8
.\" TODO: more x-refs
.Sh HISTORY
